// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnBp7DKlRAy-qlRM_IoT2N27NiC2yqfg',
    appId: '1:455937122552:web:8278a56e6a2aa55db75b0d',
    messagingSenderId: '455937122552',
    projectId: 'alexandria-2c577',
    authDomain: 'alexandria-2c577.firebaseapp.com',
    storageBucket: 'alexandria-2c577.appspot.com',
    measurementId: 'G-93T6RL3P42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsj9Qdc-tzhpJfnFHHHBYpmjUtzH4iTY',
    appId: '1:455937122552:android:10031ef1dfe22df7b75b0d',
    messagingSenderId: '455937122552',
    projectId: 'alexandria-2c577',
    storageBucket: 'alexandria-2c577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPsU7T32TWQz1jwnvPl8y1wCBCxWIXUg',
    appId: '1:455937122552:ios:52b5631226541778b75b0d',
    messagingSenderId: '455937122552',
    projectId: 'alexandria-2c577',
    storageBucket: 'alexandria-2c577.appspot.com',
    iosClientId: '455937122552-08vrnd54728hahq80n3hu6dg2n46k9fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexandria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmPsU7T32TWQz1jwnvPl8y1wCBCxWIXUg',
    appId: '1:455937122552:ios:52b5631226541778b75b0d',
    messagingSenderId: '455937122552',
    projectId: 'alexandria-2c577',
    storageBucket: 'alexandria-2c577.appspot.com',
    iosClientId: '455937122552-08vrnd54728hahq80n3hu6dg2n46k9fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexandria',
  );
}
